/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ColumnSettings: typeof import('./src/components/ColumnSettings.vue')['default']
    FilterControl: typeof import('./src/components/FilterControl.vue')['default']
    MoveToListDialog: typeof import('./src/components/MoveToListDialog.vue')['default']
    ProspectCardList: typeof import('./src/components/ProspectCardList.vue')['default']
    ProspectDetail: typeof import('./src/components/ProspectDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultDetail: typeof import('./src/components/SearchResultDetail.vue')['default']
    SortControl: typeof import('./src/components/SortControl.vue')['default']
  }
}
