import frappe

# Full Google Places API (New) place type list with readable labels.
# Source: https://developers.google.com/maps/documentation/places/web-service/place-types
DEFAULT_CATEGORIES = [
	# ── Food & Drink ──────────────────────────────────────────────────────────
	("Restaurant",                  "restaurant"),
	("Fast Food",                   "fast_food_restaurant"),
	("Cafe",                        "cafe"),
	("Coffee Shop",                 "coffee_shop"),
	("Bar",                         "bar"),
	("Bar & Grill",                 "bar_and_grill"),
	("Bakery",                      "bakery"),
	("Pizza",                       "pizza_restaurant"),
	("Sushi",                       "sushi_restaurant"),
	("Chinese Restaurant",          "chinese_restaurant"),
	("Indian Restaurant",           "indian_restaurant"),
	("Italian Restaurant",          "italian_restaurant"),
	("Mexican Restaurant",          "mexican_restaurant"),
	("Japanese Restaurant",         "japanese_restaurant"),
	("Thai Restaurant",             "thai_restaurant"),
	("Korean Restaurant",           "korean_restaurant"),
	("Vietnamese Restaurant",       "vietnamese_restaurant"),
	("Greek Restaurant",            "greek_restaurant"),
	("Mediterranean Restaurant",    "mediterranean_restaurant"),
	("French Restaurant",           "french_restaurant"),
	("Seafood Restaurant",          "seafood_restaurant"),
	("Steakhouse",                  "steak_house"),
	("Breakfast / Brunch",          "breakfast_restaurant"),
	("Hamburger Restaurant",        "hamburger_restaurant"),
	("Sandwich Shop",               "sandwich_shop"),
	("Ramen Restaurant",            "ramen_restaurant"),
	("Buffet",                      "buffet_restaurant"),
	("Fine Dining",                 "fine_dining_restaurant"),
	("Ice Cream Shop",              "ice_cream_shop"),
	("Juice Shop",                  "juice_shop"),
	("Tea House",                   "tea_house"),
	("Bagel Shop",                  "bagel_shop"),
	("Food Court",                  "food_court"),
	("Vegan Restaurant",            "vegan_restaurant"),
	("Vegetarian Restaurant",       "vegetarian_restaurant"),
	("Confectionery / Candy",       "confectionery"),
	("Meal Delivery",               "meal_delivery"),
	("Meal Takeaway",               "meal_takeaway"),
	# ── Health & Medical ──────────────────────────────────────────────────────
	("Dentist",                     "dentist"),
	("Dental Clinic",               "dental_clinic"),
	("Doctor / Physician",          "doctor"),
	("Hospital",                    "hospital"),
	("Pharmacy",                    "pharmacy"),
	("Drugstore",                   "drugstore"),
	("Physiotherapist",             "physiotherapist"),
	("Chiropractor",                "chiropractor"),
	("Optometrist",                 "optometrist"),
	("Orthodontist",                "orthodontist"),
	("Veterinary Care",             "veterinary_care"),
	("Medical Lab",                 "medical_lab"),
	("Emergency Room",              "emergency_room"),
	("Mental Health Clinic",        "mental_health_clinic"),
	("Skin Care Clinic",            "skin_care_clinic"),
	("Blood Bank",                  "blood_bank"),
	# ── Professional Services ─────────────────────────────────────────────────
	("Lawyer / Legal",              "lawyer"),
	("Accountant",                  "accounting"),
	("Insurance Agency",            "insurance_agency"),
	("Real Estate Agency",          "real_estate_agency"),
	("Bank",                        "bank"),
	("ATM",                         "atm"),
	("Financial Planner",           "financial_planner"),
	("Travel Agency",               "travel_agency"),
	("Moving Company",              "moving_company"),
	("Courier / Delivery",          "courier_service"),
	("Marketing Agency",            "media_agency"),
	("Event Planner",               "event_planner"),
	("Notary Public",               "notary_public"),
	("Staffing Agency",             "staffing_agency"),
	("Corporate Office",            "corporate_office"),
	("Title Company",               "title_company"),
	("Tax / Bookkeeper",            "bookkeeper"),
	# ── Trades & Home Services ────────────────────────────────────────────────
	("Plumber",                     "plumber"),
	("Electrician",                 "electrician"),
	("General Contractor",          "general_contractor"),
	("Roofing Contractor",          "roofing_contractor"),
	("Pest Control",                "pest_control"),
	("Locksmith",                   "locksmith"),
	("HVAC / Heating",              "hvac_contractor"),
	("Painter",                     "painter"),
	("Landscaper",                  "landscaper"),
	("Swimming Pool Contractor",    "swimming_pool_contractor"),
	("Solar Energy Contractor",     "solar_energy_contractor"),
	("Interior Designer",           "interior_designer"),
	("Sign Maker",                  "sign_maker"),
	("Glazier / Window",            "glazier"),
	("Dry Cleaning / Laundry",      "dry_cleaning"),
	("Laundry",                     "laundry"),
	# ── Automotive ────────────────────────────────────────────────────────────
	("Car Repair / Auto Shop",      "car_repair"),
	("Car Dealer",                  "car_dealer"),
	("Used Car Dealer",             "used_car_dealer"),
	("Car Rental",                  "car_rental"),
	("Car Wash",                    "car_wash"),
	("Gas Station",                 "gas_station"),
	("Tire Shop",                   "tire_shop"),
	("Auto Parts Store",            "auto_parts_store"),
	("EV Charging Station",         "electric_vehicle_charging_station"),
	("Motorcycle Dealer",           "motorcycle_dealer"),
	("Motorcycle Repair",           "motorcycle_repair_shop"),
	("Truck Dealer",                "truck_dealer"),
	("Truck Rental",                "truck_rental_agency"),
	# ── Beauty & Wellness ─────────────────────────────────────────────────────
	("Hair Salon",                  "hair_salon"),
	("Beauty Salon",                "beauty_salon"),
	("Nail Salon",                  "nail_salon"),
	("Spa",                         "spa"),
	("Barber Shop",                 "barber_shop"),
	("Tattoo Parlor",               "tattoo_parlor"),
	("Massage",                     "massage"),
	("Tanning Salon",               "tanning_studio"),
	# ── Fitness & Recreation ──────────────────────────────────────────────────
	("Gym / Fitness Center",        "gym"),
	("Yoga Studio",                 "yoga"),
	("Sports Club",                 "sports_club"),
	("Martial Arts School",         "martial_arts_school"),
	("Swimming Pool",               "swimming_pool"),
	("Golf Course",                 "golf_course"),
	("Tennis Court",                "tennis_court"),
	("Bowling Alley",               "bowling_alley"),
	("Ice Skating Rink",            "ice_skating_rink"),
	("Ski Resort",                  "ski_resort"),
	# ── Retail & Shopping ─────────────────────────────────────────────────────
	("Grocery Store",               "grocery_store"),
	("Supermarket",                 "supermarket"),
	("Convenience Store",           "convenience_store"),
	("Clothing Store",              "clothing_store"),
	("Shoe Store",                  "shoe_store"),
	("Electronics Store",           "electronics_store"),
	("Hardware Store",              "hardware_store"),
	("Home Improvement Store",      "home_improvement_store"),
	("Home Goods Store",            "home_goods_store"),
	("Furniture Store",             "furniture_store"),
	("Jewelry Store",               "jewelry_store"),
	("Bookstore",                   "book_store"),
	("Pet Store",                   "pet_store"),
	("Florist",                     "florist"),
	("Gift Shop",                   "gift_shop"),
	("Bicycle Store",               "bicycle_store"),
	("Sporting Goods",              "sporting_goods_store"),
	("Toy Store",                   "toy_store"),
	("Liquor Store",                "liquor_store"),
	("Shopping Mall",               "shopping_mall"),
	("Department Store",            "department_store"),
	("Pawn Shop",                   "pawn_shop"),
	("Cell Phone Store",            "cell_phone_store"),
	("Music Store",                 "music_store"),
	("Photo / Camera Store",        "photo_studio"),
	# ── Education & Training ──────────────────────────────────────────────────
	("School",                      "school"),
	("University / College",        "university"),
	("Preschool",                   "preschool"),
	("Child Care Agency",           "child_care_agency"),
	("Driving School",              "driving_school"),
	("Language School",             "language_school"),
	("Vocational / Trade School",   "vocational_school"),
	("Training Center",             "training_center"),
	("Library",                     "library"),
	# ── Lodging & Hospitality ─────────────────────────────────────────────────
	("Hotel",                       "hotel"),
	("Motel",                       "motel"),
	("Bed & Breakfast",             "bed_and_breakfast"),
	("Hostel",                      "hostel"),
	("Campground",                  "campground"),
	("Extended Stay Hotel",         "extended_stay_hotel"),
	("RV Park",                     "rv_park"),
	# ── Entertainment ─────────────────────────────────────────────────────────
	("Movie Theater",               "movie_theater"),
	("Night Club",                  "night_club"),
	("Amusement Park",              "amusement_park"),
	("Museum",                      "museum"),
	("Art Gallery",                 "art_gallery"),
	("Casino",                      "casino"),
	("Comedy Club",                 "comedy_club"),
	("Zoo",                         "zoo"),
	("Aquarium",                    "aquarium"),
	("Performing Arts Theater",     "performing_arts_theater"),
	("Banquet Hall / Event Venue",  "banquet_hall"),
	("Wedding Venue",               "wedding_venue"),
	("Karaoke",                     "karaoke"),
	("Video Arcade",                "video_arcade"),
	# ── Government & Public Services ─────────────────────────────────────────
	("Post Office",                 "post_office"),
	("Police Station",              "police"),
	("Fire Station",                "fire_station"),
	("City Hall",                   "city_hall"),
	("Courthouse",                  "courthouse"),
	("Embassy",                     "embassy"),
	("Local Government Office",     "local_government_office"),
	# ── Logistics & Infrastructure ────────────────────────────────────────────
	("Storage Facility",            "storage"),
	("Recycling Center",            "recycling_center"),
	("Truck Stop",                  "truck_stop"),
	("Parking",                     "parking"),
	("Airport",                     "airport"),
	("Bus Station",                 "bus_station"),
	("Train Station",               "train_station"),
	("Subway Station",              "subway_station"),
	("Gas / Fuel Station",          "gas_station"),
	# ── Community & Non-Profit ────────────────────────────────────────────────
	("Funeral Home",                "funeral_home"),
	("Animal Shelter",              "animal_shelter"),
	("Pet Grooming",                "pet_grooming"),
	("Community Center",            "community_center"),
	("Tourist Information",         "tourist_information_center"),
	# ── Places of Worship ─────────────────────────────────────────────────────
	("Church",                      "church"),
	("Mosque",                      "mosque"),
	("Synagogue",                   "synagogue"),
	("Hindu Temple",                "hindu_temple"),
]


def after_install():
	_setup_crm_custom_fields()
	_populate_default_categories()


def _setup_crm_custom_fields():
	"""Create custom fields on CRM Lead and CRM Organization."""
	FIELDS = [
		dict(dt='CRM Lead', fieldname='custom_prospect', label='Source Prospect',
		     fieldtype='Link', options='Prospect', insert_after='source', read_only=1),
		dict(dt='CRM Lead', fieldname='custom_google_rating', label='Google Rating',
		     fieldtype='Float', insert_after='custom_prospect', read_only=1),
		dict(dt='CRM Organization', fieldname='custom_prospect', label='Source Prospect',
		     fieldtype='Link', options='Prospect', insert_after='website', read_only=1),
		dict(dt='CRM Organization', fieldname='custom_google_rating', label='Google Rating',
		     fieldtype='Float', insert_after='custom_prospect', read_only=1),
		dict(dt='CRM Organization', fieldname='custom_google_maps_url', label='Google Maps URL',
		     fieldtype='Data', options='URL', insert_after='custom_google_rating', read_only=1),
		dict(dt='CRM Organization', fieldname='custom_address_text', label='Address',
		     fieldtype='Small Text', insert_after='custom_google_maps_url', read_only=1),
	]
	for f in FIELDS:
		name = f'{f["dt"]}-{f["fieldname"]}'
		if not frappe.db.exists('Custom Field', name):
			cf = frappe.new_doc('Custom Field')
			cf.update(f)
			cf.insert(ignore_permissions=True)
	frappe.db.commit()


def _populate_default_categories():
	"""Seed Prospecting Settings with the default Google place type list."""
	settings = frappe.get_single('Prospecting Settings')
	if settings.categories:
		return  # already configured — don't overwrite user's list
	for label, value in DEFAULT_CATEGORIES:
		settings.append('categories', {'label': label, 'value': value})
	settings.save(ignore_permissions=True)
	frappe.db.commit()
